### PR TITLE
Added some algorithm courses.

### PR DESCRIPTION
**Pull request by mkghosh**
@ericdouglas please review the courses I have added.

### CODE REVIEW

**Comment by crmackay** [comment]
some of these are duplicates...i believe the sedgewick course from coursera is listed twice at least

**Comment by ericdouglas** [comment]
@crmackay good catch :smile: 

@mkghosh the [Analysis of Algorithms](https://www.coursera.org/course/aofa) is duplicated. Could you remove this one?

Thank you all! :pray:

**Comment by mkghosh** [comment]
@ericdouglas sure I am going to remove that. Thanks after today I will be more cautious about duplicates.

**Comment by mkghosh** [comment]
@crmackay thank you for pointing me out about the duplication.

**Comment by mkghosh** [comment]
@ericdouglas I have removed the duplicate course please have a look again.

**Comment by ericdouglas** [comment]
@mkghosh thanks! :clap:

**Comment by mkghosh** [comment]
@ericdouglas you are welcome.

**Pull request merged**
