### PR TITLE
Added Extra courses

### PR DESCRIPTION
**Pull request by mkghosh**
I have committed 3 different commits and in these 3 commits I have added 5 more courses. In first commit I have added [Introduction to Linux](https://github.com/mkghosh/computer-science/blob/master/extras/courses.md#operating-systems) course in the Operating Systems section. In the Second and third commit I have added 4 java programming learning course in the [Programming Paradigms](https://github.com/mkghosh/computer-science/blob/master/extras/courses.md#programming-paradigms) Section.

### CODE REVIEW

**Comment by ni8mr** [comment]
You can comment this in your commits instead of opening an issue.

**Comment by mkghosh** [comment]
I didn't know that. That is why I have created the pull request. @ni8mr

**Comment by mkghosh** [comment]
But If I don't open a pull request how can my commits be merged with the master branch. @ni8mr

**Comment by ni8mr** [comment]
Sorry my bad, i thought this was an **issue**. Ignore my ignorance.

**Comment by ericdouglas** [comment]
@mkghosh thank you so much for helping us! :pray: 

I have some considerations about your PR:

- The Introduction to Programming with Java Part 1 and 2 should be in the "Introduction to Computer Science" section.
- Introduction to Java Programming – Part 1 and 2 should not be part of our curriculum because we don't have a specific field for programming languages. Our focus is more related to CS concepts instead of programming languages. We are "language agnostic", students can create their projects in whatever language they want. If we start to add such kind of courses, our list will be endless.
- Introduction to Linux :+1:

Can you refactor your PR?

Thanks in advance!

**Comment by mkghosh** [comment]
@ericdouglas I am glad to know that my addition did help you. I will try to refactor it now but I am not sure that I can do it just now because I am using an Android mobile to see this but any way I will try now if successful I will create another pull request. Thank you too.

**Comment by mkghosh** [comment]
@ericdouglas I tried to mean that it helped the community. Thanks.

**Comment by ericdouglas** [comment]
@mkghosh don't worry. You can fix it later, no problem! :smile:

**Comment by mkghosh** [comment]
@ericdouglas I have updated the file as you suggest. Please review the changes.

**Comment by ericdouglas** [comment]
@mkghosh perfect! Thank you so much! :pray:

**Comment by mkghosh** [comment]
@ericdouglas you are most welcome.

**Pull request merged**
