### PR TITLE
Add link to Dive into Machine Learning

### PR DESCRIPTION
**Pull request by hangtwenty**
Humbly submitted ...

Add link to  (Optional) Hack-first, fun introduction to get you confident and motivated -- Dive into Machine Learning. The point of Dive into Machine Learning is to launch you right into Prof. Andrew Ng's Machine Learning course, which is the course already linked here!

Not sure if this breaks with formatting too much but I think it would be a good contribution. With OSS and self-motivated stuff it's always good to have ways to build momentum and keep you motivated ... I designed this guide specifically to help kick-start people into doing an OSS course, with the preferred course being Prof. Andrew Ng's course, which you already recommend.

Looking forward to hearing what you think.

Thank you for this invaluable resource! As someone reared on OSS and self-taught material ... it's wonderful to find something so complete, that I can relay to interested friends.

### CODE REVIEW

**Comment by ericdouglas** [comment]
@hangtwenty Hey! Thank you for your contribution!

But sadly this really breaks our curriculum format. 

If we include one optional resource, we will open the precedent to add one optional resource for each topic, which is not a good thing for us generally speaking.

You can share your material in our [community channels](https://github.com/open-source-society/computer-science#community), and futurely we can also recommend your material in our blog/newsletter. :smile:

**Comment by hangtwenty** [comment]
Hey @ericdouglas , that's a great point. Makes total sense to me.

**Comment by hangtwenty** [comment]
To the community channels I go! Thanks!

**Comment by ericdouglas** [comment]
@hangtwenty thank you so much for your interest in help us!

I'm glad that you understood :smile:

**Comment by hangtwenty** [comment]
:beers:

**Pull request closed without merging**
