### PR TITLE
added cybrary.it courses

### PR DESCRIPTION
**Pull request by mkghosh**
@ericdouglas I have added new courses from [cybrary.it](www.cybrary.it) could you please review the convention and tell if anything needs to be changed.

### CODE REVIEW

**Comment by ericdouglas** [comment]
@mkghosh thank you!

You need to fix just two things:

- Pull/add the Linear Algebra - Foundations to Frontiers (LAFF) course to your fork (it was removed in your PR)
- Remove the `X modules` information in the Duration column. It's better to keep this cell empty in such occasion, because "module" has no meaning in this column.

**Comment by mkghosh** [comment]
@ericdouglas The first thing I have done earlier and the second one I will do now thanks.

**Comment by mkghosh** [comment]
@ericdouglas I have removed modules from the courses you can review now

**Comment by mkghosh** [comment]
I have tried to pull the latest work from upstream but it is not working can you tell me what to do my repo is saying already up to date. @ericdouglas

**Comment by ericdouglas** [comment]
@mkghosh thanks! :pray:

**Comment by mkghosh** [comment]
@ericdouglas you are welcome

**Pull request merged**
