### PR TITLE
Updated course info and added direct links to specializations.

### PR DESCRIPTION
**Pull request by MirzaI**
See commit messages.

### CODE REVIEW

**Comment by MirzaI** [comment]
@ericdouglas Waiting for your response regarding the agile-development-using-ruby-rails course. Will change my commit according to your comments.

**Comment by ericdouglas** [comment]
@MirzaI just remove the "From Nand to Tetris (Part 2, coming in May/June 2016)" row and update the current version of the curriculum following [these](https://github.com/open-source-society/computer-science/pull/263#issuecomment-192719698) instructions.

I agree with you, we can remove the Startup Engineering course. I'll do this after your PR.

Thank you for your help! Great contribution :clap:

**Comment by MirzaI** [comment]
@ericdouglas Ok, everything should be okay now. Tried to remove the old commits so it's cleaner, but could not figure it out. Need more experience with git.

Let me know if I missed anything.

**Comment by ericdouglas** [comment]
@MirzaI perfect! :clap: Thank you!

**Pull request merged**
