### PR TITLE
Added course called "Discrete optimization"

### PR DESCRIPTION
**Pull request by QtRoS**
Very useful and interesting course with challengeable tasks and fantastic instructor.

### CODE REVIEW

**Comment by ericdouglas** [comment]
@QtRoS you added the course in the `Algorithms` section, but on the course's page is telling that this course is about `Artificial Intelligence`.

Can you add in the correct section?

You can also remove `of study` in the Duration column.

Many thanks for helping us to improve our resources! :pray:

**Comment by QtRoS** [comment]
@ericdouglas to be honest - this course is not about algorithms and not about AI :) It studies programming techniques of solving NP hard problems. But I'll move it since course site is telling us that it is about AI.

**Comment by QtRoS** [comment]
Finally done :)

**Comment by ericdouglas** [comment]
@QtRoS perfect, thank you! :pray:

**Pull request merged**
