### PR TITLE
Add Git - the simple guide to the prerequisite section

### PR DESCRIPTION
**Pull request by ramirio**
git - the simple guide is a good resource because provide a lot of information of the git workflow in a few minutes and it's available in 16 languages, good for someone that maybe have some difficult with English.

### CODE REVIEW

**Comment by mseyne** [comment]
:+1:

**Comment by ericdouglas** [comment]
@ramirio 

thank you for your help! :pray: 

Could you also make more two things?

- Bump our Curriculum Version to **1.2.1** [here](https://github.com/open-source-society/computer-science#change-log), because you're adding a resource in our file.
- Add a little explanation in our [CHANGELOG](https://github.com/open-source-society/computer-science/blob/master/CHANGELOG.md) file, saying what you're doing. More explanations about CHANGELOG files [here](http://keepachangelog.com/). The text will be something like this:
  ```
  [1.2.1] 2015-10-11

  ### Added
  - Article Git - the simple guide to the prerequisite section.
  ```

**Comment by ramirio** [comment]
done :+1:

**Comment by ericdouglas** [comment]
@ramirio many thanks! :smile:

**Pull request merged**
